# 东西南北定位
import tkinter
top=tkinter.Tk()
comm1=tkinter.Button(top,text='Northwest')
comm1.pack(anchor='nw')
comm2=tkinter.Button(top,text='North')
comm2.pack(anchor='n')
comm3=tkinter.Button(top,text='Northeast')
comm3.pack(anchor='ne')
comm4=tkinter.Button(top,text='West')
comm4.pack(anchor='w')
comm5=tkinter.Button(top,text='Centered')
comm5.pack(anchor='center')
comm6=tkinter.Button(top,text='East')
comm6.pack(anchor='e')
comm7=tkinter.Button(top,text='Southwest')
comm7.pack(anchor='sw')
comm8=tkinter.Button(top,text='South')
comm8.pack(anchor='s')
comm9=tkinter.Button(top,text='Southeast')
comm9.pack(anchor='se')
top.mainloop()